<a href="https://colab.research.google.com/github/Lunes313/Phyton/blob/main/PythonWithColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iteracion 6

Ciclos en python

Uso del while

In [ ]:
i=1
while i < 10:
  print(i)
  i= i+1

1
2
3
4
5
6
7
8
9


**EJERCICIO 1**

SE CREA UNA LISTA CON LOS NUMEROS DEL 1 AL 10

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


COMIENZAN A HACERSE ITERACIONES PARA DESPLAZAR LOS NUMEROS AL FINAL

Iteracion 1

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
print(l)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 1]



Iteracion 2



In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
print(l)

[3, 4, 5, 6, 7, 8, 9, 10, 1, 2]


Iteracion 3

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
print(l)

[4, 5, 6, 7, 8, 9, 10, 1, 2, 3]


Iteracion 4

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
print(l)

[5, 6, 7, 8, 9, 10, 1, 2, 3, 4]


Iteracion 5

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
print(l)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]


Iteracion 6

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
for i in l:
  l.remove(6)
  l.append(6)
print(l)

[7, 8, 9, 10, 1, 2, 3, 4, 5, 6]


Iteracion 7

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
for i in l:
  l.remove(6)
  l.append(6)
for i in l:
  l.remove(7)
  l.append(7)
  
print(l)

[8, 9, 10, 1, 2, 3, 4, 5, 6, 7]


Iteracion 8

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
for i in l:
  l.remove(6)
  l.append(6)
for i in l:
  l.remove(7)
  l.append(7)
for i in l:
  l.remove(8)
  l.append(8)
print(l)

[9, 10, 1, 2, 3, 4, 5, 6, 7, 8]


Iteracion 9

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
for i in l:
  l.remove(6)
  l.append(6)
for i in l:
  l.remove(7)
  l.append(7)
for i in l:
  l.remove(8)
  l.append(8)
for i in l:
  l.remove(9)
  l.append(9)
print(l)

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Iteracion 10

In [ ]:
l=[]
i= 1
while i<=10:
  l.append(i)
  i=i+1
for i in l:
  l.remove(1)
  l.append(1)
for i in l:
  l.remove(2)
  l.append(2)
for i in l:
  l.remove(3)
  l.append(3)
for i in l:
  l.remove(4)
  l.append(4)
for i in l:
  l.remove(5)
  l.append(5)
for i in l:
  l.remove(6)
  l.append(6)
for i in l:
  l.remove(7)
  l.append(7)
for i in l:
  l.remove(8)
  l.append(8)
for i in l:
  l.remove(9)
  l.append(9)
for i in l:
  l.remove(10)
  l.append(10)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**EJERCICIO 2**

-se crea una lista con 20 numeros aleatorios y se muestra 

In [ ]:
import random 
lista = []
for i in range (0,20):
  lista.append(random.randint(1,100))
print(lista)




[70, 65, 82, 91, 47, 23, 100, 32, 58, 61, 80, 1, 1, 11, 1, 27, 86, 38, 50, 33]


- se muestra la lista sin los numeros repetidos gracias al uso de la funcion set() que se usa para para mostras un conjunto con los elementos sin repetir 

In [ ]:
import random 
lista = []
for i in range (0,20):
  lista.append(random.randint(1,100))
print(lista)  #esta lista es diferente a la del anterior ejemplo por que genera otros numeros aleatorios 
set(lista)

[82, 42, 25, 28, 76, 47, 6, 56, 44, 29, 42, 1, 74, 10, 2, 47, 28, 85, 80, 18]


{1, 2, 6, 10, 18, 25, 28, 29, 42, 44, 47, 56, 74, 76, 80, 82, 85}

**EJERCICIO 3**

-se crea una matriz de 10*10 con numeros random

In [ ]:
import numpy as np 
  
array = np.random.randint(1000, size=(10, 10)) 
print(array) 

[[ 69 289  11 236 185 134 234 514 857 547]
 [480 375  85 633 729 594  88  18 463 565]
 [890   9 416 179 995  32 192 450 584 981]
 [235 439 542 779 328 797   8 789 363 712]
 [854 157 554 891 767 992 181 924 754 165]
 [474 214 542 590 259 581 312 736 382 466]
 [607  52  19 117 878 796 349 192  73 609]
 [142 171 844 987 193  70   3 304 317 664]
 [540  78  52 684 419 474 964  70 271 263]
 [892 841 544 963 506 961 613 198 907 784]]


-hallar el numero mayor 

In [ ]:
import numpy as np 
  
array = np.random.randint(1000, size=(10, 10)) 
print(array) 

mayor = array[0][0]

for fila in array:
  for valor in fila:
    if valor > mayor:
        mayor=valor

print("")
print("")
print("el numero mayor es:" ,(mayor))
np.where(array==mayor)

[[803 560 777  90 476 750 156 241 790 606]
 [186  35 372 381 599 943 111 872 431 782]
 [403 528 965 754 220 969 520 379 423  55]
 [619 349 244 553 839 900  25 664  58 357]
 [753 740 686 705 912 880 461  97  27 461]
 [266 846  50 458 898 597  77 848 156 198]
 [546 265 365 319 834 750 185 516 553 521]
 [226  17 665  86 198 739 517  37 305 831]
 [432 783 716 299 432 257 891  38 981 915]
 [782 545 177 798 728 898 138   7 646 557]]


el numero mayor es: 981


(array([8]), array([8]))

-hallar el numero menor

In [166]:
import numpy as np 
  
array = np.random.randint(1000, size=(10, 10)) 
print(array) 

menor = array[0][0]

for fila in array:
  for valor in fila:
    if valor < menor:
        menor=valor

print("")
print("")
print("el numero menor es:" ,(menor))
np.where(array==menor)

[[827 300  35 335 324 290 235  97 823 833]
 [333 493 338 704  60 504 299 475 716 466]
 [315 931 558 973 416 697 817 266 342 425]
 [783  30  94 691 784 707 488 215 341 198]
 [257 898 507 933 186 916 758 784 302 272]
 [ 84 814 449 813 398 213 996 781 251  29]
 [341 703 257 271 439 213 536  60 401 421]
 [ 30 931 197 236 965 435 304 519 933 458]
 [600 198 341 221 647 118 249 346 436  52]
 [620 239 278 381 372 168 744 544 167 342]]


el numero menor es: 29


(array([5]), array([9]))

**EJERCICIO 4**

-SE CREA UNA MATRIZ DE 10X10 Y LUEGO SE SUMA LA PRIMERA COLUMNA

In [169]:
import numpy as np 
  
array = np.random.randint(1000, size=(10, 10)) 
print(array)

suma = np.sum(array, axis=0)
print(suma)


[[293 790 887 398 428 112 309  56 573 540]
 [953 969 841 535 818 348 727 473  31 369]
 [421  15 458 192 988 537 778 950 331 536]
 [215 704 720 294 973 716 743 460 938 876]
 [423 353 837 257 277 635 978 382 947 851]
 [954 543 791 573 191 593  28 257 621  43]
 [468 312 813 567 474 477 729 328 651 760]
 [806 109 123 818 808 313 536 476   8 867]
 [708 808 933 818 548 806 954 265 162 807]
 [934 487 646 542 337 395 354 940  44 746]]
[6175 5090 7049 4994 5842 4932 6136 4587 4306 6395]
